### ISSUE TITLE
Issues with 3.1.0 and Electron 14

### ISSUE THREAD

**Issue by msavin** [Meteor-Community-Packages/meteor-desktop#12]
Hey - I just installed 3.1.0, bumped Electron to 14.2.9 and ran Meteor update. Unfortunately I cannot build or start the app anymore. I'm getting back the following errors:

On build step: 
```
ERROR  electronApp:  error while transpiling or minifying:  TypeError: Invalid Version: undefined
    at new SemVer (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at Function.lt (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/lib/index.js:275:15
    at /Users/max/Documents/GitHub/App/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
    at ElectronApp.transpileAndMinify (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/electronApp.js:856:24)
    at ElectronApp.build (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/electronApp.js:451:24)
    at MeteorDesktop.buildInstaller (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/index.js:115:9)
```

On startup:
```
=> Errors prevented startup:                  
   
   While processing files with communitypackages:meteor-desktop-bundler (for target web.cordova):
   /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11: Invalid Version: undefined
   at new SemVer (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
   at compare (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
   at Function.lt (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
   at /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/lib/index.js:275:15
   at /Users/max/Documents/GitHub/App/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
   at packages/meteor-desktop-bundler/bundler.js:815:28
   at Function.time (/Users/max/.meteor/packages/meteor-tool/.2.7.3.i3v35y.kfyte++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
   at MeteorDesktopBundler.processFilesForTarget (packages/meteor-desktop-bundler/bundler.js:499:17)
```

**Comment by evan-coygo** [comment]
This seems to be in `bundler.js` because it's not calling the babel preset with the proper [PluginAPI object](https://github.com/babel/babel/blob/90fb82a535db396f14a57ea1913b6604b9b1480f/packages/babel-core/src/config/helpers/config-api.js#L20-L26)

This is the current code
```js
const preset = babelPresetEnv({ assertVersion: () => { } }, { targets: { node: '12' } });
```

@babel/preset-env internally calls semver.js and is expecting that argument to contain a `.version` property like this

```js
const preset = babelPresetEnv({
  version: <version String>,
  assertVersion: () => { }
}, { targets: { node: '12' } });
```

**Comment by a4xrbj1** [comment]
I'm getting the same error as @msavin - all was fine in version 3.0.1

**Comment by vpalos** [comment]
> This seems to be in `bundler.js` because it's not calling the babel preset with the proper [PluginAPI object](https://github.com/babel/babel/blob/90fb82a535db396f14a57ea1913b6604b9b1480f/packages/babel-core/src/config/helpers/config-api.js#L20-L26)
> 
> This is the current code
> 
> ```js
> const preset = babelPresetEnv({ assertVersion: () => { } }, { targets: { node: '12' } });
> ```
> 
> @babel/preset-env internally calls semver.js and is expecting that argument to contain a `.version` property like this
> 
> ```js
> const preset = babelPresetEnv({
>   version: <version String>,
>   assertVersion: () => { }
> }, { targets: { node: '12' } });
> ```

This issue is still happening. I've tried to install meteor-desktop in an existing project and encountered this exact problem.

Moreover, the exact same kind of call is made in the `lib/electronApp.js` file: https://github.com/Meteor-Community-Packages/meteor-desktop/blob/master/lib/electronApp.js#L855

**Comment by StorytellerCZ** [comment]
@vpalos do you think this is a good fix: https://github.com/Meteor-Community-Packages/meteor-desktop/pull/13/commits/1ea4fc0789257d1aae98b44d2f718b0540f34bf2

**Comment by dd137** [comment]
@StorytellerCZ For what it's worth, I think it's a good solution for now. It solves the issue for me.

To get always up-to-date preset-env versions, we could also do:
- `version: require('../package.json').dependencies['@babel/preset-env']` in electronApp.js, and
-  `version: this.getPackageJsonField('dependencies')['@babel/preset-env']` in bundler.js.

Would that be better?
