### ISSUE TITLE
Transpiling and minifying TypeError: api.caller is not a function

### ISSUE THREAD

**Issue by iokill** [Meteor-Community-Packages/meteor-desktop#38]
Since updating to meteor-desktop v3.2.0 I'm getting an error when running `npm run desktop -- build-installer ...`:

```
INFO  electronApp:  excluding files from packing
INFO  electronApp:  transpiling and uglifying
ERROR  electronApp:  error while transpiling or minifying:  TypeError: api.caller is not a function
    at builder (C:\Users\X\Y\node_modules\@babel\preset-env\src\index.ts:390:13)
    at C:\Users\X\Y\node_modules\@babel\helper-plugin-utils\src\index.ts:62:12
    at ElectronApp.transpileAndMinify (C:\Users\X\Y\node_modules\@meteor-community\meteor-desktop\lib\electronApp.js:854:33)
    at ElectronApp.build (C:\Users\X\Y\node_modules\@meteor-community\meteor-desktop\lib\electronApp.js:451:24)
    at MeteorDesktop.buildInstaller (C:\Users\X\Y\node_modules\@meteor-community\meteor-desktop\lib\index.js:111:9)
```

It appears that the `meteor-desktop-bundler` package is affected too as I'm getting a similar error from it.

**To Reproduce**

Simply running `npm run desktop -- build-installer ...` is enough for me once I've updated to meteor-desktop v3.2.0.

**Expected behavior**

No error during installer build.

**Versions (please complete the following information):**
 - Meteor version: 2.14
 - Package version: 3.2.0

**Additional context**

I've tried to track this down and it appears that some refactoring of `@babel/preset-env` seems to have caused this: https://github.com/babel/babel/pull/15988. Also note the comment there why `?.` was removed when accessing `api.caller`, so I believe this is an issue in meteor-desktop rather than `preset-env`.

A quick and dirty fix for me was to simply provide a dummy `caller` function in the object passed to `preset-env` like this:

```diff
diff --git a/lib/electronApp.js b/lib/electronApp.js
index eecf05f..fb6f3ca 100644
--- a/lib/electronApp.js
+++ b/lib/electronApp.js
@@ -853,7 +853,8 @@ export default class ElectronApp {

         const preset = presetEnv({
             version: require('../package.json').dependencies['@babel/preset-env'],
-            assertVersion: () => { }
+            assertVersion: () => { },
+            caller: () => false,
         }, { targets: { node: '14' } });

         const { data: files } = await this.$.utils.readDir(this.$.env.paths.desktopTmp.root);
```
Though this seems to me like a hack as this will break again once `present-env` changes their API. Isn't there a more stable way for `meteor-desktop` to call babel with options from `preset-env`?

Just for reference, here is some issues I've found which might be related:
- #12 
- https://github.com/babel/babel/issues/10646

**Comment by iokill** [comment]
Appears to be a dup of #37, so closing this. Sorry, that issue was created while I was creating mine 😅
