### ISSUE TITLE
Update shell.js to fix broken build after Meteor 2.3 + node 14

### ISSUE THREAD

**Issue by evan-coygo** [Meteor-Community-Packages/meteor-desktop#6]
See https://github.com/wojtkowiak/meteor-desktop/issues/303

Projects on Meteor 2.3+ will see this error when building on local
```
internal/fs/utils.js:811
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1521:5)
    at Module.<anonymous> (/home/evan/.meteor/packages/meteor-tool/.2.6.0.vf20yq.9k39d++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1493:23)
    at packages/meteor-desktop-bundler/bundler.js:869:48
    at runAsync (/home/evan/devel/coygo/webapp/node_modules/@babel/core/lib/transformation/index.js:40:10)
    at /home/evan/devel/coygo/webapp/node_modules/@babel/core/lib/transform.js:34:34
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by evan-coygo** [comment]
@KoenLav can we get this published to npm so we can release fixes like this? See #5
