### ISSUE TITLE
ENOENT. spawn /usr/bin/python error after updating macOS 12.3 (Monterey)

### ISSUE THREAD

**Issue by a4xrbj1** [Meteor-Community-Packages/meteor-desktop#9]
MacOS 12.3 removed built-in Python 2, build process breaks for MacOS in Electron since then.

```
ERROR  electronBuilder:  error while building installer:  Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/andreaswest/Documents/workspace/frontend/node_modules/builder-util/src/util.ts:133:18
    at exithandler (child_process.js:390:5)
    at ChildProcess.errorhandler (child_process.js:402:5)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

See also [Electron-Builder issue #6726](https://github.com/electron-userland/electron-builder/issues/6726)

**To Reproduce**

Build an Electron app for MacOS (desktopHCP turned off) with MacOS 12.3 or higher

**Expected behavior**

Electron MacOS app should be build without any error/problem

**Versions (please complete the following information):**
 - Meteor version: 2.5.6
 - METEOR-DESKTOP v3.0.1
 - electron@10.1.3
 - electron-builder@22.14.13

**Additional context**

Tried installing Python 2.7 manually but it still breaks.

**Comment by a4xrbj1** [comment]
Is fixed by upgrading electron-builder to version 23.0.2
